/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    ChatDrawer: typeof import('./src/components/layout/ChatDrawer.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    LuckyWheel: typeof import('./src/components/shop/LuckyWheel.vue')['default']
    MatchResultScreen: typeof import('./src/components/multiplayer/MatchResultScreen.vue')['default']
    Medal: typeof import('./src/components/achievements/Medal.vue')['default']
    RadarScan: typeof import('./src/components/games/RadarScan.vue')['default']
    RadioSignal: typeof import('./src/components/games/RadioSignal.vue')['default']
    RemoteCursor: typeof import('./src/components/RemoteCursor.vue')['default']
    RhymeSquad: typeof import('./src/components/games/RhymeSquad.vue')['default']
    RightSidebar: typeof import('./src/components/layout/RightSidebar.vue')['default']
    RouletteOverlay: typeof import('./src/components/games/RouletteOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scratch_radio: typeof import('./src/components/games/scratch_radio.vue')['default']
    Scratch_radio_utf8: typeof import('./src/components/games/scratch_radio_utf8.vue')['default']
    Scratch_symmetry: typeof import('./src/components/games/scratch_symmetry.vue')['default']
    Scratch_symmetry_utf8: typeof import('./src/components/games/scratch_symmetry_utf8.vue')['default']
    SpelledRosco: typeof import('./src/components/games/SpelledRosco.vue')['default']
    SyllableQuest: typeof import('./src/components/games/SyllableQuest.vue')['default']
    SymmetryBreaker: typeof import('./src/components/games/SymmetryBreaker.vue')['default']
    WordConstruction: typeof import('./src/components/games/WordConstruction.vue')['default']
  }
}
