FROM node:22-slim

WORKDIR /app

# Instalamos dependencias primero para aprovechar la caché
COPY package*.json ./
RUN npm install

COPY . .

# Exponemos el puerto de Vite
EXPOSE 3001

# IMPORTANTE: Usamos --host 0.0.0.0 para que sea accesible fuera del contenedor
# y forzamos el puerto 3001
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3001"]