# Etapa 1: Build
FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servidor Web ligero (Nginx)
FROM nginx:stable-alpine AS production-stage

# Copiamos los archivos estáticos generados en la etapa anterior
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Exponemos el puerto estándar web
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]