export const ACHIEVEMENTS = [
  {
    id: 1,
    title: 'Primer Vuelo',
    description: 'Completa 1 misión.',
    icon: 'rocket-launch',
    type: 'bronze',
    metric: 'missions',
    goal: 1,
    metricLabel: 'Misiones',
  },
  {
    id: 2,
    title: 'Tripulante Activo',
    description: 'Completa 5 misiones.',
    icon: 'gamepad-variant',
    type: 'bronze',
    metric: 'missions',
    goal: 5,
    metricLabel: 'Misiones',
  },
  {
    id: 3,
    title: 'Veterano Estelar',
    description: 'Completa 20 misiones.',
    icon: 'star-four-points',
    type: 'silver',
    metric: 'missions',
    goal: 20,
    metricLabel: 'Misiones',
  },
  {
    id: 4,
    title: 'Primer Botín',
    description: 'Acumula 1.200 monedas.',
    icon: 'currency-usd-circle',
    type: 'bronze',
    metric: 'coins',
    goal: 1200,
    metricLabel: 'Monedas',
  },
  {
    id: 5,
    title: 'Fortuna Galáctica',
    description: 'Acumula 3.000 monedas.',
    icon: 'cash-multiple',
    type: 'gold',
    metric: 'coins',
    goal: 3000,
    metricLabel: 'Monedas',
  },
  {
    id: 6,
    title: 'Primer Coleccionable',
    description: 'Consigue 1 objeto en inventario.',
    icon: 'package-variant-closed',
    type: 'bronze',
    metric: 'inventory',
    goal: 1,
    metricLabel: 'Objetos',
  },
  {
    id: 7,
    title: 'Coleccionista',
    description: 'Consigue 5 objetos en inventario.',
    icon: 'treasure-chest',
    type: 'silver',
    metric: 'inventory',
    goal: 5,
    metricLabel: 'Objetos',
  },
  {
    id: 8,
    title: 'Museo Orbital',
    description: 'Consigue 10 objetos en inventario.',
    icon: 'diamond-stone',
    type: 'gold',
    metric: 'inventory',
    goal: 10,
    metricLabel: 'Objetos',
  },
  {
    id: 9,
    title: 'Subiendo de Rango',
    description: 'Alcanza el nivel 3.',
    icon: 'chevron-triple-up',
    type: 'bronze',
    metric: 'level',
    goal: 3,
    metricLabel: 'Nivel',
  },
  {
    id: 10,
    title: 'Capitán Novato',
    description: 'Alcanza el nivel 5.',
    icon: 'shield-star',
    type: 'silver',
    metric: 'level',
    goal: 5,
    metricLabel: 'Nivel',
  },
  {
    id: 11,
    title: 'Comandante',
    description: 'Alcanza el nivel 8.',
    icon: 'crown',
    type: 'gold',
    metric: 'level',
    goal: 8,
    metricLabel: 'Nivel',
  },
  {
    id: 12,
    title: 'Energía Infinita',
    description: 'Consigue 500 XP.',
    icon: 'atom-variant',
    type: 'platinum',
    metric: 'xp',
    goal: 500,
    metricLabel: 'XP',
  },
  {
    id: 13,
    title: 'Estratega Galáctico',
    description: 'Completa 10 misiones.',
    icon: 'brain',
    type: 'silver',
    metric: 'missions',
    goal: 10,
    metricLabel: 'Misiones',
  },
  {
    id: 14,
    title: 'Mercader de Estrellas',
    description: 'Acumula 2.000 monedas.',
    icon: 'hand-coin',
    type: 'silver',
    metric: 'coins',
    goal: 2000,
    metricLabel: 'Monedas',
  },
  {
    id: 15,
    title: 'Héroe del Cosmos',
    description: 'Completa 50 misiones.',
    icon: 'trophy-award',
    type: 'gold',
    metric: 'missions',
    goal: 50,
    metricLabel: 'Misiones',
  },
  {
    id: 16,
    title: 'Magnate de la Nebulosa',
    description: 'Acumula 5.000 monedas.',
    icon: 'bank',
    type: 'gold',
    metric: 'coins',
    goal: 5000,
    metricLabel: 'Monedas',
  },
  {
    id: 17,
    title: 'Soberano del Vacío',
    description: 'Alcanza el nivel 10.',
    icon: 'weather-night',
    type: 'platinum',
    metric: 'level',
    goal: 10,
    metricLabel: 'Nivel',
  },
  {
    id: 18,
    title: 'Conquistador de Galaxias',
    description: 'Consigue 1.000 XP.',
    icon: 'orbit',
    type: 'platinum',
    metric: 'xp',
    goal: 1000,
    metricLabel: 'XP',
  },
];
