/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    LeftSidebar: typeof import('./src/components/layout/LeftSidebar.vue')['default']
    LuckyWheel: typeof import('./src/components/shop/LuckyWheel.vue')['default']
    RadarScan: typeof import('./src/components/games/RadarScan.vue')['default']
    RightSidebar: typeof import('./src/components/layout/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpelledRosco: typeof import('./src/components/games/SpelledRosco.vue')['default']
    WordConstruction: typeof import('./src/components/games/WordConstruction.vue')['default']
  }
}
