/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/achievements/achievements': RouteRecordInfo<'/achievements/achievements', '/achievements/achievements', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/plans/plans': RouteRecordInfo<'/plans/plans', '/plans/plans', Record<never, never>, Record<never, never>>,
    '/profile/profile': RouteRecordInfo<'/profile/profile', '/profile/profile', Record<never, never>, Record<never, never>>,
    '/shop/shop': RouteRecordInfo<'/shop/shop', '/shop/shop', Record<never, never>, Record<never, never>>,
    '/training/multiplayer': RouteRecordInfo<'/training/multiplayer', '/training/multiplayer', Record<never, never>, Record<never, never>>,
    '/training/singleplayer': RouteRecordInfo<'/training/singleplayer', '/training/singleplayer', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/achievements/achievements.vue': {
      routes: '/achievements/achievements'
      views: never
    }
    'src/pages/auth/login.vue': {
      routes: '/auth/login'
      views: never
    }
    'src/pages/auth/register.vue': {
      routes: '/auth/register'
      views: never
    }
    'src/pages/home/index.vue': {
      routes: '/home/'
      views: never
    }
    'src/pages/plans/plans.vue': {
      routes: '/plans/plans'
      views: never
    }
    'src/pages/profile/profile.vue': {
      routes: '/profile/profile'
      views: never
    }
    'src/pages/shop/shop.vue': {
      routes: '/shop/shop'
      views: never
    }
    'src/pages/training/multiplayer.vue': {
      routes: '/training/multiplayer'
      views: never
    }
    'src/pages/training/singleplayer.vue': {
      routes: '/training/singleplayer'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
