// backend/src/constants/rosco.js

const ROSCO_WORDS = [
    { char: 'A', question: 'Cos rocallós que orbita al voltant del Sol.', answer: 'ASTEROIDE', hieroglyphs: ['☄️', '🪨', '🌌'] },
    { char: 'C', question: 'Astre de gel i pols amb una cua lluminosa.', answer: 'COMETA', hieroglyphs: ['☄️', '❄️', '✨'] },
    { char: 'E', question: 'Esfera de gas que emet llum i calor.', answer: 'ESTRELLA', hieroglyphs: ['⭐', '🔥', '✨'] },
    { char: 'G', question: 'Sistema enorme d\'estrelles units per la gravetat.', answer: 'GALAXIA', hieroglyphs: ['🌀', '🌌', '✨'] },
    { char: 'N', question: 'Núvol de gas on neixen noves estrelles.', answer: 'NEBULOSA', hieroglyphs: ['☁️', '🌈', '👶'] },
    { char: 'P', question: 'Cos celest que orbita una estrella.', answer: 'PLANETA', hieroglyphs: ['🌍', '💫', '☀️'] },
    { char: 'S', question: 'L\'estrella central del nostre sistema.', answer: 'SOL', hieroglyphs: ['☀️', '🔥', '🦁'] },
    { char: 'T', question: 'Instrument per observar objectes llunyans a l\'espai.', answer: 'TELESCOPI', hieroglyphs: ['🔭', '👁️', '🌌'] },
    { char: 'U', question: 'Tot el que existeix: matèria, energia, espai i temps.', answer: 'UNIVERS', hieroglyphs: ['🌌', '♾️', '⚛️'] },
    { char: 'O', question: 'Trajectòria corba d\'un objecte a l\'espai.', answer: 'ORBITA', hieroglyphs: ['🔄', '🌍', '🌌'] },
    { char: 'G', question: 'Felí domèstic molt independent i juganer.', answer: 'GAT', hieroglyphs: ['🐱', '🏠', '🧶'] },
    { char: 'A', question: 'Au rapinyaire de gran envergadura, símbol de llibertat.', answer: 'AGUILA', hieroglyphs: ['🦅', '🏔️', '🗽'] },
    { char: 'D', question: 'Mamífer marí molt intel·ligent que viu en grups.', answer: 'DOLFI', hieroglyphs: ['🐬', '🌊', '🧠'] },
    { char: 'E', question: 'El mamífer terrestre més gran del món.', answer: 'ELEFANT', hieroglyphs: ['🐘', '🌳', '🐘'] },
    { char: 'L', question: 'Gran felí conegut com el rei de la selva.', answer: 'LLEO', hieroglyphs: ['🦁', '👑', '🌿'] },
    { char: 'T', question: 'Rèptil amb closca dura que es mou lentament.', answer: 'TORTUGA', hieroglyphs: ['🐢', '🐚', '🐌'] },
    { char: 'C', question: 'Animal amb vuit tentacles que viu al fons del mar.', answer: 'CRANC', hieroglyphs: ['🦀', '🐚', '🏖️'] },
    { char: 'P', question: 'Ocell tropical de colors vius que pot imitar sons.', answer: 'LLORO', hieroglyphs: ['🦜', '🌴', '🗣️'] },
    { char: 'A', question: 'La unitat bàsica de la matèria.', answer: 'ATOM', hieroglyphs: ['⚛️', '🔬', '1️⃣'] },
    { char: 'C', question: 'Unitat bàsica dels éssers vius.', answer: 'CELULA', hieroglyphs: ['🧬', '🔬', '🥚'] },
    { char: 'G', question: 'Força que atrau els objectes cap al centre de la Terra.', answer: 'GRAVETAT', hieroglyphs: ['🍎', '⬇️', '🌍'] },
    { char: 'O', question: 'Gas esencial per a la respiració dels éssers vius.', answer: 'OXIGEN', hieroglyphs: ['💨', '🫁', '🌳'] },
    { char: 'H', question: 'L\'element químic més lleuger de l\'univers.', answer: 'HIDROGEN', hieroglyphs: ['🎈', '1️⃣', '💧'] },
    { char: 'E', question: 'Capacitat per fer un treball o produir un canvi.', answer: 'ENERGIA', hieroglyphs: ['⚡', '🔋', '🔥'] },
    { char: 'M', question: 'Aparell que fa que les coses petites es vegin grans.', answer: 'MICROSCOPI', hieroglyphs: ['🔬', '👁️', '🤏'] },
    { char: 'V', question: 'Rapidesa amb què un objecte canvia de posició.', answer: 'VELOCITAT', hieroglyphs: ['🏃', '💨', '⏱️'] },
    { char: 'M', question: 'Gran massa d\'aigua salada que cobreix la Terra.', answer: 'MAR', hieroglyphs: ['🌊', '⛵', '🧂'] },
    { char: 'V', question: 'Muntanya que pot fer erupció amb lava.', answer: 'VOLCA', hieroglyphs: ['🌋', '🔥', '🏔️'] },
    { char: 'R', question: 'Corrent natural d\'aigua que desemboca al mar.', answer: 'RIU', hieroglyphs: ['💧', '🏞️', '🐟'] },
    { char: 'I', question: 'Porció de terra envoltada d\'aigua per tots els costats.', answer: 'ILLA', hieroglyphs: ['🏝️', '🌊', '🌴'] },
    { char: 'D', question: 'Zona àrida amb molt poques precipitacions.', answer: 'DESERT', hieroglyphs: ['🏜️', '☀️', '🌵'] },
    { char: 'S', question: 'Gran extensió de bosc tropical amb molta biodiversitat.', answer: 'SELVA', hieroglyphs: ['🌳', '🐒', '🦜'] },
    { char: 'L', question: 'Massa d\'aigua dolça envoltada de terra.', answer: 'LLAC', hieroglyphs: ['💧', '🌲', '🦢'] },
    { char: 'P', question: 'Fruita allargada i groga molt energètica.', answer: 'PLATAN', hieroglyphs: ['🍌', '🟡', '🐒'] },
    { char: 'T', question: 'Fruita vermella molt usada en amanides i salses.', answer: 'TOMAQUET', hieroglyphs: ['🍅', '🥗', '🍝'] },
    { char: 'F', question: 'Preparat comestible fet amb llet coagulada.', answer: 'FORMATGE', hieroglyphs: ['🧀', '🧀', '🐭'] },
    { char: 'X', question: 'Dolç elaborat amb cacau.', answer: 'XOCOLATA', hieroglyphs: ['🍫', '🍫', '😋'] },
    { char: 'P', question: 'Plat italià amb base de massa, tomàquet i formatge.', answer: 'PIZZA', hieroglyphs: ['🍕', '🇮🇹', '🍕'] },
    { char: 'M', question: 'Producte dolç que fan les abelles.', answer: 'MEL', hieroglyphs: ['🍯', '🐝', '🍯'] },
    { char: 'A', question: 'Fruita vermella o verda que creix als arbres.', answer: 'POMA', hieroglyphs: ['🍎', '🍏', '🌳'] },
    { char: 'F', question: 'Esport d\'equip amb una pilota rodona i porteries.', answer: 'FUTBOL', hieroglyphs: ['⚽', '🥅', '🏟️'] },
    { char: 'B', question: 'Esport on es llança una pilota a una cistella.', answer: 'BASQUET', hieroglyphs: ['🏀', '🗑️', '🏀'] },
    { char: 'N', question: 'Esport aquàtic on es fan braçades a la piscina.', answer: 'NATACIO', hieroglyphs: ['🏊', '🌊', '🏊'] },
    { char: 'T', question: 'Esport de raqueta amb una pilota sobre una xarxa.', answer: 'TENNIS', hieroglyphs: ['🎾', '🏸', '🎾'] },
    { char: 'C', question: 'Esport on es pedala amb dues rodes.', answer: 'CICLISME', hieroglyphs: ['🚴', '🚲', '🚴'] },
    { char: 'R', question: 'Esport d\'equip amb una pilota ovalada.', answer: 'RUGBY', hieroglyphs: ['🏉', '🏉', '🏟️'] },
    { char: 'E', question: 'Esport d\'hivern on es llisca per la neu.', answer: 'ESQUI', hieroglyphs: ['⛷️', '❄️', '🏔️'] },
    { char: 'R', question: 'Màquina programable que pot fer tasques automàtiques.', answer: 'ROBOT', hieroglyphs: ['🤖', '⚙️', '⚡'] },
    { char: 'I', question: 'Xarxa global que connecta ordinadors de tot el món.', answer: 'INTERNET', hieroglyphs: ['🌐', '💻', '📶'] },
    { char: 'P', question: 'Acció de crear instruccions perquè un ordinador faci una tasca.', answer: 'PROGRAMAR', hieroglyphs: ['💻', '⌨️', '📜'] },
    { char: 'W', question: 'Lloc a internet on pots consultar informació.', answer: 'WEB', hieroglyphs: ['🕸️', '💻', '🔍'] },
    { char: 'D', question: 'Informació emmagatzemada en sistemes informàtics.', answer: 'DADES', hieroglyphs: ['📊', '📁', '💾'] },
    { char: 'S', question: 'Dispositiu electrònic de butxaca amb pantalla tàctil.', answer: 'SMARTPHONE', hieroglyphs: ['📱', '🤳', '📲'] },
    { char: 'B', question: 'Gran extensió de terreny cobert d\'arbres.', answer: 'BOSC', hieroglyphs: ['🌲', '🌳', '🦌'] },
    { char: 'F', question: 'Part de la planta que sol ser de colors i atrau insectes.', answer: 'FLOR', hieroglyphs: ['🌸', '🐝', '💐'] },
    { char: 'A', question: 'Planta gran amb tronc llenyós i branques.', answer: 'ARBRE', hieroglyphs: ['🌳', '🪵', '🍃'] },
    { char: 'P', question: 'Precipitació d\'aigua que cau dels núvols.', answer: 'PLUJA', hieroglyphs: ['🌧️', '☔', '💧'] },
    { char: 'N', question: 'Massa visible de gotes d\'aigua al cel.', answer: 'NUVOL', hieroglyphs: ['☁️', '☁️', '🌈'] },
    { char: 'L', question: 'Font natural de llum que ve del Sol.', answer: 'LLUM', hieroglyphs: ['💡', '☀️', '🔦'] },
    { char: 'V', question: 'Moviment de l\'aire a l\'atmosfera.', answer: 'VENT', hieroglyphs: ['🌬️', '🍃', '🪁'] },
    { char: 'C', question: 'Edifici fortificat medieval amb torres i muralles.', answer: 'CASTELL', hieroglyphs: ['🏰', '🛡️', '👑'] },
    { char: 'M', question: 'Lloc on s\'exposen obres d\'art i objectes històrics.', answer: 'MUSEU', hieroglyphs: ['🏛️', '🖼️', '🗿'] },
    { char: 'L', question: 'Conjunt de signes escrits que serveix per comunicar-se.', answer: 'LLENGUA', hieroglyphs: ['👅', '🗣️', '📜'] },
    { char: 'G', question: 'Instrument de cordes molt popular en el rock.', answer: 'GUITARRA', hieroglyphs: ['🎸', '🎶', '🤘'] },
    { char: 'P', question: 'Instrument de tecles blanques i negres.', answer: 'PIANO', hieroglyphs: ['🎹', '🎶', '🎹'] },
    { char: 'B', question: 'Instrument de percussió que es toca amb baquetes.', answer: 'BATERIA', hieroglyphs: ['🥁', '🎶', '🥁'] },
    { char: 'F', question: 'Instrument de vent de fusta amb forats.', answer: 'FLAUTA', hieroglyphs: ['🎶', '🌬️', '🦯'] },
    { char: 'M', question: 'Art de combinar sons de forma agradable.', answer: 'MUSICA', hieroglyphs: ['🎶', '🎼', '🎧'] },
];

const ROSCO_ROLES = {
    TRANSLATOR: 'translator',
    GUESSER: 'guesser',
    SENDER: 'sender',
};

module.exports = {
    ROSCO_WORDS,
    ROSCO_ROLES
};
