export const EMOJI_CATEGORIES = [
  { id: 'faces', label: 'Caras', icon: '😀' },
  { id: 'animals', label: 'Animales', icon: '🐶' },
  { id: 'food', label: 'Comida', icon: '🍎' },
  { id: 'activities', label: 'Actividades', icon: '⚽' },
  { id: 'travel', label: 'Viajes', icon: '🚀' },
  { id: 'objects', label: 'Objetos', icon: '💡' },
  { id: 'symbols', label: 'Símbolos', icon: '❤️' },
]

export const EMOJI_LIBRARY = [
  // Faces
  { char: '😀', category: 'faces', tags: 'feliz happy sonrisa smile' },
  { char: '😂', category: 'faces', tags: 'risa laugh llorar risa riure' },
  { char: '🤣', category: 'faces', tags: 'risa laugh riure' },
  { char: '😊', category: 'faces', tags: 'feliz happy sonrisa smile feliç' },
  { char: '😇', category: 'faces', tags: 'angel inocente àngel' },
  { char: '😍', category: 'faces', tags: 'enamorado love' },
  { char: '🤩', category: 'faces', tags: 'estrella ojos wow' },
  { char: '😘', category: 'faces', tags: 'beso kiss amor love petó' },
  { char: '😋', category: 'faces', tags: 'comida rico yummy' },
  { char: '😛', category: 'faces', tags: 'lengua tongue llengua' },
  { char: '😜', category: 'faces', tags: 'lengua guiño' },
  { char: '🤪', category: 'faces', tags: 'loco crazy boig' },
  { char: '🤨', category: 'faces', tags: 'duda sceptic' },
  { char: '🧐', category: 'faces', tags: 'monoculo investigar' },
  { char: '🤓', category: 'faces', tags: 'empollon nerd' },
  { char: '😎', category: 'faces', tags: 'guay cool sol sunglasses' },
  { char: '🥳', category: 'faces', tags: 'fiesta party celebracion festa' },
  { char: '😏', category: 'faces', tags: 'pillo' },
  { char: '😒', category: 'faces', tags: 'aburrido bored' },
  { char: '😞', category: 'faces', tags: 'triste sad trist' },
  { char: '😔', category: 'faces', tags: 'triste sad trist' },
  { char: '😟', category: 'faces', tags: 'preocupado worried' },
  { char: '😕', category: 'faces', tags: 'confundido confused' },
  { char: '🙁', category: 'faces', tags: 'triste sad trist' },
  { char: '☹️', category: 'faces', tags: 'muy triste sad' },
  { char: '😣', category: 'faces', tags: 'sufrimiento' },
  { char: '😖', category: 'faces', tags: 'confundido' },
  { char: '😫', category: 'faces', tags: 'cansado tired cansat' },
  { char: '😩', category: 'faces', tags: 'cansado tired cansat' },
  { char: '🥺', category: 'faces', tags: 'por favor please' },
  { char: '😢', category: 'faces', tags: 'llorar cry triste sad plorar' },
  { char: '😭', category: 'faces', tags: 'llorar mucho cry sad plorar' },
  { char: '😤', category: 'faces', tags: 'enfadado angry' },
  { char: '😠', category: 'faces', tags: 'enfadado angry enfadat' },
  { char: '😡', category: 'faces', tags: 'muy enfadado angry rojo red enfadat' },
  { char: '🤬', category: 'faces', tags: 'insulto enfadado' },
  { char: '🤯', category: 'faces', tags: 'cabeza explota wow mindblown' },
  { char: '😳', category: 'faces', tags: 'sonrojado' },
  { char: '🥵', category: 'faces', tags: 'calor hot rojo red' },
  { char: '🥶', category: 'faces', tags: 'frio cold azul blue fred' },
  { char: '😱', category: 'faces', tags: 'miedo fear susto wow por' },
  { char: '😨', category: 'faces', tags: 'miedo fear por' },
  { char: '😰', category: 'faces', tags: 'miedo miedo por' },
  { char: '😥', category: 'faces', tags: 'alivio' },
  { char: '😓', category: 'faces', tags: 'sudor' },
  { char: '🤗', category: 'faces', tags: 'abrazo hug abraçada' },
  { char: '🤔', category: 'faces', tags: 'pensar think duda' },
  { char: '🤭', category: 'faces', tags: 'secreto' },
  { char: '🤫', category: 'faces', tags: 'silencio shh silenci' },
  { char: '🤥', category: 'faces', tags: 'mentira lie pinocho mentida' },
  { char: '😶', category: 'faces', tags: 'sin palabras' },
  { char: '😐', category: 'faces', tags: 'neutral' },
  { char: '😑', category: 'faces', tags: 'sin expresion' },
  { char: '😬', category: 'faces', tags: 'mueca' },
  { char: '🙄', category: 'faces', tags: 'ojos arriba roll eyes' },
  { char: '😯', category: 'faces', tags: 'sorpresa surprise wow' },
  { char: '😦', category: 'faces', tags: 'sorpresa surprise' },
  { char: '😧', category: 'faces', tags: 'sorpresa surprise' },
  { char: '😮', category: 'faces', tags: 'sorpresa surprise wow' },
  { char: '😲', category: 'faces', tags: 'sorpresa surprise wow' },
  { char: '😴', category: 'faces', tags: 'dormir sleep' },
  { char: '🤤', category: 'faces', tags: 'baba' },
  { char: '😪', category: 'faces', tags: 'dormir sleep' },
  { char: '😵', category: 'faces', tags: 'mareado' },
  { char: '🤐', category: 'faces', tags: 'boca cerrada' },
  { char: '🥴', category: 'faces', tags: 'borracho' },
  { char: '🤢', category: 'faces', tags: 'asco' },
  { char: '🤮', category: 'faces', tags: 'vomitar' },
  { char: '🤧', category: 'faces', tags: 'estornudar' },
  { char: '🤒', category: 'faces', tags: 'fiebre enfermo febre' },
  { char: '🤕', category: 'faces', tags: 'herida enfermo ferida' },
  { char: '🤑', category: 'faces', tags: 'dinero money diners' },
  { char: '🤠', category: 'faces', tags: 'vaquero cowboy' },
  { char: '😈', category: 'faces', tags: 'diablo devil malo' },
  { char: '👿', category: 'faces', tags: 'diablo devil' },
  { char: '👹', category: 'faces', tags: 'ogro monster' },
  { char: '👺', category: 'faces', tags: 'duende monster' },
  { char: '🤡', category: 'faces', tags: 'payaso clown pallasso' },
  { char: '💩', category: 'faces', tags: 'caca poop' },
  { char: '👻', category: 'faces', tags: 'fantasma ghost miedo por' },
  { char: '💀', category: 'faces', tags: 'calavera skull muerte death calavera' },
  { char: '☠️', category: 'faces', tags: 'pirata death muerte' },
  { char: '👽', category: 'faces', tags: 'alien espacio space' },
  { char: '👾', category: 'faces', tags: 'monstruo space' },
  { char: '🤖', category: 'faces', tags: 'robot' },
  { char: '🎃', category: 'faces', tags: 'calabaza halloween carbassa' },

  // Animals
  { char: '🐶', category: 'animals', tags: 'perro dog animal mascota gos' },
  { char: '🐱', category: 'animals', tags: 'gato cat animal mascota gat' },
  { char: '🐭', category: 'animals', tags: 'raton mouse animal ratolí' },
  { char: '🐹', category: 'animals', tags: 'hamster animal mascota hàmster' },
  { char: '🐰', category: 'animals', tags: 'conejo rabbit animal conill' },
  { char: '🦊', category: 'animals', tags: 'zorro fox animal guineu' },
  { char: '🐻', category: 'animals', tags: 'oso bear animal os' },
  { char: '🐼', category: 'animals', tags: 'panda animal' },
  { char: '🐨', category: 'animals', tags: 'koala animal' },
  { char: '🐯', category: 'animals', tags: 'tigre tiger animal' },
  { char: '🦁', category: 'animals', tags: 'leon lion animal lleó' },
  { char: '🐮', category: 'animals', tags: 'vaca cow animal' },
  { char: '🐷', category: 'animals', tags: 'cerdo pig animal porc' },
  { char: '🐸', category: 'animals', tags: 'rana frog animal granota' },
  { char: '🐵', category: 'animals', tags: 'mono monkey animal mico' },
  { char: '🐔', category: 'animals', tags: 'pollo chicken gallina animal gallina' },
  { char: '🐧', category: 'animals', tags: 'pinguino penguin animal pingüí' },
  { char: '🐦', category: 'animals', tags: 'pajaro bird animal ocell' },
  { char: '🐤', category: 'animals', tags: 'pollito ocellet' },
  { char: '🦆', category: 'animals', tags: 'pato duck animal ànec' },
  { char: '🦅', category: 'animals', tags: 'aguila eagle animal àguila' },
  { char: ' owls', category: 'animals', tags: 'buho owl animal mussol' },
  { char: '🦉', category: 'animals', tags: 'buho owl animal mussol' },
  { char: '🦇', category: 'animals', tags: 'murcielago bat animal ratpenat' },
  { char: '🐺', category: 'animals', tags: 'lobo wolf animal llop' },
  { char: '🐗', category: 'animals', tags: 'jabalí boar animal senglar' },
  { char: '🐴', category: 'animals', tags: 'caballo horse animal cavall' },
  { char: '🦄', category: 'animals', tags: 'unicornio fantasy unicorni' },
  { char: '🐝', category: 'animals', tags: 'abeja bee insecto abella' },
  { char: '🐛', category: 'animals', tags: 'gusano bug insecto cuc' },
  { char: '🦋', category: 'animals', tags: 'mariposa butterfly insecto papallona' },
  { char: '🐌', category: 'animals', tags: 'caracol snail insecto caragol' },
  { char: '🐞', category: 'animals', tags: 'mariquita ladybug insecto marieta' },
  { char: '🐜', category: 'animals', tags: 'hormiga ant insecto formiga' },
  { char: '🦗', category: 'animals', tags: 'grillo cricket insecto grill' },
  { char: '🕷️', category: 'animals', tags: 'araña spider insecto aranya' },
  { char: '🦂', category: 'animals', tags: 'escorpion scorpion insecto escorpí' },
  { char: '🐢', category: 'animals', tags: 'tortuga turtle animal' },
  { char: '🐍', category: 'animals', tags: 'serpiente snake animal serp' },
  { char: '🦎', category: 'animals', tags: 'lagartija lizard animal sargantana' },
  { char: '🦖', category: 'animals', tags: 'dinosaurio t-rex' },
  { char: '🐙', category: 'animals', tags: 'pulpo octopus mar ocean pop' },
  { char: '🦑', category: 'animals', tags: 'calamar squid mar ocean' },
  { char: '🦐', category: 'animals', tags: 'gamba shrimp mar ocean' },
  { char: '🦞', category: 'animals', tags: 'langosta lobster mar ocean llagosta' },
  { char: '🦀', category: 'animals', tags: 'cangrejo crab mar ocean cranc' },
  { char: '🐡', category: 'animals', tags: 'pez globo pufferfish mar ocean peix' },
  { char: '🐠', category: 'animals', tags: 'pez tropical fish mar ocean peix' },
  { char: '🐟', category: 'animals', tags: 'pez fish mar ocean peix' },
  { char: '🐬', category: 'animals', tags: 'delfin dolphin mar ocean dofí' },
  { char: '🐳', category: 'animals', tags: 'ballena whale mar ocean balena' },
  { char: '🦈', category: 'animals', tags: 'tiburon shark mar ocean tauró' },
  { char: '🐊', category: 'animals', tags: 'cocodrilo crocodile animal cocodril' },

  // Food
  { char: '🍎', category: 'food', tags: 'manzana apple fruta fruit comida food poma' },
  { char: '🍐', category: 'food', tags: 'pera pear fruta fruit comida food' },
  { char: '🍊', category: 'food', tags: 'naranja orange fruta fruit comida food taronja' },
  { char: '🍋', category: 'food', tags: 'limon lemon fruta fruit comida food llimona' },
  { char: '🍌', category: 'food', tags: 'platano banana fruta fruit comida food plàtan' },
  { char: '🍉', category: 'food', tags: 'sandia watermelon fruta fruit comida food síndria' },
  { char: '🍇', category: 'food', tags: 'uvas grapes fruta fruit comida food raïm' },
  { char: '🍓', category: 'food', tags: 'fresa strawberry fruta fruit comida food maduixa' },
  { char: '🍒', category: 'food', tags: 'cerezas cherries fruta fruit comida food cireres' },
  { char: '🍑', category: 'food', tags: 'melocoton peach fruta fruit comida food préssec' },
  { char: '🍍', category: 'food', tags: 'piña pineapple fruta fruit comida food pinya' },
  { char: '🥥', category: 'food', tags: 'coco coconut fruta fruit comida food' },
  { char: '🥝', category: 'food', tags: 'kiwi fruta fruit comida food' },
  { char: '🍅', category: 'food', tags: 'tomate tomato verdura vegetable comida food tomàquet' },
  { char: '🥦', category: 'food', tags: 'brocoli broccoli verdura vegetable comida food bròquil' },
  { char: '🥑', category: 'food', tags: 'aguacate avocado comida food alvocat' },
  { char: '🍆', category: 'food', tags: 'berenjena eggplant verdura vegetable comida food albergínia' },
  { char: '🥔', category: 'food', tags: 'patata potato verdura vegetable comida food' },
  { char: '🥕', category: 'food', tags: 'zanahoria carrot verdura vegetable comida food pastanaga' },
  { char: '🌽', category: 'food', tags: 'maiz corn comida food blat de moro' },
  { char: '🌶️', category: 'food', tags: 'picante chili comida food' },
  { char: '🍄', category: 'food', tags: 'seta mushroom comida food bolets' },
  { char: '🥜', category: 'food', tags: 'cacahuetes peanuts comida food cacauets' },
  { char: '🥐', category: 'food', tags: 'cruasan croissant comida food pan cruixent' },
  { char: '🍞', category: 'food', tags: 'pan bread comida food pa' },
  { char: '🥨', category: 'food', tags: 'pretzel comida food' },
  { char: '🧀', category: 'food', tags: 'queso cheese comida food formatge' },
  { char: '🥩', category: 'food', tags: 'carne meat comida food carn' },
  { char: '🍗', category: 'food', tags: 'pollo chicken comida food pollastre' },
  { char: '🍔', category: 'food', tags: 'hamburguesa burger comida food fastfood' },
  { char: '🍟', category: 'food', tags: 'patatas fritas fries comida food fastfood patates' },
  { char: '🍕', category: 'food', tags: 'pizza comida food fastfood' },
  { char: 'hotdogs', category: 'food', tags: 'perrito caliente hotdog comida food fastfood' },
  { char: '🌭', category: 'food', tags: 'perrito caliente hotdog comida food fastfood' },
  { char: '🌮', category: 'food', tags: 'taco comida food' },
  { char: '🌯', category: 'food', tags: 'burrito comida food' },
  { char: '🍳', category: 'food', tags: 'huevo egg comida food desayuno ou' },
  { char: '🥚', category: 'food', tags: 'huevo egg comida food desayuno ou' },
  { char: '🥣', category: 'food', tags: 'sopa soup comida food' },
  { char: '🍿', category: 'food', tags: 'palomitas popcorn comida food cine crispetes' },
  { char: '🍱', category: 'food', tags: 'bento comida food japones' },
  { char: ' sushi', category: 'food', tags: 'sushi comida food japones' },
  { char: '🍣', category: 'food', tags: 'sushi comida food japones' },
  { char: '🍦', category: 'food', tags: 'helado icecream postre sweet comida food gelat' },
  { char: '🍩', category: 'food', tags: 'donut postre sweet comida food' },
  { char: '🍪', category: 'food', tags: 'galleta cookie postre sweet comida food galeta' },
  { char: '🎂', category: 'food', tags: 'pastel cake postre sweet comida food cumple pastís' },
  { char: '🍰', category: 'food', tags: 'pastel cake postre sweet comida food cumple pastís' },
  { char: '🍫', category: 'food', tags: 'chocolate postre sweet comida food xocolata' },
  { char: '🍬', category: 'food', tags: 'caramelo candy postre sweet comida food' },
  { char: '🍭', category: 'food', tags: 'piruleta lollipop postre sweet comida food' },
  { char: '🍮', category: 'food', tags: 'flan postre sweet comida food' },
  { char: '🍯', category: 'food', tags: 'miel honey postre sweet comida food mel' },
  { char: '☕', category: 'food', tags: 'cafe coffee bebida drink cafè' },
  { char: '🍵', category: 'food', tags: 'te tea bebida drink tè' },
  { char: '🥤', category: 'food', tags: 'refresco soda bebida drink' },
  { char: '🍺', category: 'food', tags: 'cerveza beer bebida drink alcohol cervesa' },
  { char: '🍷', category: 'food', tags: 'vino wine bebida drink alcohol vi' },
  { char: '🍹', category: 'food', tags: 'coctel cocktail bebida drink còctel' },

  // Activities
  { char: '⚽', category: 'activities', tags: 'futbol soccer deporte sport pelota ball' },
  { char: '🏀', category: 'activities', tags: 'baloncesto basketball deporte sport pelota ball bàsquet' },
  { char: '🏈', category: 'activities', tags: 'rugby deporte sport pelota ball' },
  { char: '⚾', category: 'activities', tags: 'beisbol baseball deporte sport pelota ball' },
  { char: '🎾', category: 'activities', tags: 'tenis tennis deporte sport pelota ball' },
  { char: '🏐', category: 'activities', tags: 'voleyball deporte sport pelota ball' },
  { char: '🎱', category: 'activities', tags: 'billar deporte sport pelota ball' },
  { char: '🏓', category: 'activities', tags: 'pingpong deporte sport' },
  { char: '🏸', category: 'activities', tags: 'badminton deporte sport' },
  { char: '🥅', category: 'activities', tags: 'porteria deporte sport' },
  { char: '⛳', category: 'activities', tags: 'golf deporte sport' },
  { char: '⛸️', category: 'activities', tags: 'patinaje hielo deporte sport patinatge' },
  { char: '🎣', category: 'activities', tags: 'pesca fishing deporte sport' },
  { char: '🛶', category: 'activities', tags: 'canoa kayak deporte sport' },
  { char: '🏄', category: 'activities', tags: 'surf deporte sport mar' },
  { char: '🏇', category: 'activities', tags: 'carreras caballos deporte sport cavalls' },
  { char: '🚲', category: 'activities', tags: 'ciclismo bici bike deporte sport' },
  { char: '🏆', category: 'activities', tags: 'trofeo trophy ganador winner premio trofeu' },
  { char: '🏅', category: 'activities', tags: 'medalla medal ganador winner' },
  { char: '🥇', category: 'activities', tags: 'primero first medalla' },
  { char: '🥈', category: 'activities', tags: 'segundo second medalla' },
  { char: '🥉', category: 'activities', tags: 'tercero third medalla' },
  { char: '🎸', category: 'activities', tags: 'guitarra music musica instrumento' },
  { char: '🎹', category: 'activities', tags: 'piano music musica instrumento' },
  { char: '🎷', category: 'activities', tags: 'saxofon music musica instrumento' },
  { char: '🎺', category: 'activities', tags: 'trompeta music musica instrumento' },
  { char: '🎻', category: 'activities', tags: 'violin music musica instrumento' },
  { char: '🥁', category: 'activities', tags: 'tambor music musica instrumento' },
  { char: '🎧', category: 'activities', tags: 'auriculares music musica auriculars' },
  { char: '🎤', category: 'activities', tags: 'microfono music musica cantar' },
  { char: '🎨', category: 'activities', tags: 'arte art pintura paint' },
  { char: '🎬', category: 'activities', tags: 'cine movie pelicula' },
  { char: '🎮', category: 'activities', tags: 'videojuegos game mando' },
  { char: '🕹️', category: 'activities', tags: 'videojuegos game retro' },
  { char: '🎲', category: 'activities', tags: 'dados dice juego game daus' },
  { char: '🧩', category: 'activities', tags: 'puzzle rompecabezas' },
  { char: '♟️', category: 'activities', tags: 'ajedrez chess juego' },

  // Travel
  { char: '🚗', category: 'travel', tags: 'coche car transporte transport cotxe' },
  { char: '🚕', category: 'travel', tags: 'taxi transporte transport' },
  { char: '🚌', category: 'travel', tags: 'autobus bus transporte transport autobús' },
  { char: '🏎️', category: 'travel', tags: 'carreras car transporte transport' },
  { char: '🚓', category: 'travel', tags: 'policia police transporte transport policia' },
  { char: '🚑', category: 'travel', tags: 'ambulancia transporte transport' },
  { char: '🚒', category: 'travel', tags: 'bomberos transporte transport bombers' },
  { char: '🚲', category: 'travel', tags: 'bici bike transporte transport' },
  { char: '🛵', category: 'travel', tags: 'moto transporte transport' },
  { char: '🏍️', category: 'travel', tags: 'moto transporte transport' },
  { char: '🚆', category: 'travel', tags: 'tren train transporte transport' },
  { char: '✈️', category: 'travel', tags: 'avion plane transporte transport viajar travel avió' },
  { char: '🚀', category: 'travel', tags: 'cohete rocket espacio space transporte transport coet' },
  { char: '🛸', category: 'travel', tags: 'ovni ufo espacio space alien' },
  { char: '🚁', category: 'travel', tags: 'helicoptero transporte transport helicòpter' },
  { char: '⛵', category: 'travel', tags: 'barco boat transporte transport mar vaixell' },
  { char: '🚢', category: 'travel', tags: 'crucero ship transporte transport mar vaixell' },
  { char: '🌍', category: 'travel', tags: 'tierra earth mundo world planeta planet terra' },
  { char: '🌑', category: 'travel', tags: 'luna nueva moon noche lluna' },
  { char: '🪐', category: 'travel', tags: 'saturno saturn planeta planet' },
  { char: '🌠', category: 'travel', tags: 'estrella fugaz' },

  // Objects
  { char: '💡', category: 'objects', tags: 'idea luz light bombilla llum' },
  { char: '🔍', category: 'objects', tags: 'lupa search buscar' },
  { char: '🔑', category: 'objects', tags: 'llave key clau' },
  { char: '🔒', category: 'objects', tags: 'candado lock candau' },
  { char: '🔓', category: 'objects', tags: 'candado abierto unlock' },
  { char: '🔨', category: 'objects', tags: 'martillo hammer herramienta tool martell' },
  { char: '🛠️', category: 'objects', tags: 'herramientas tools martillo pico eines' },
  { char: '⛏️', category: 'objects', tags: 'pico pickaxe herramienta tool pic' },
  { char: '⚙️', category: 'objects', tags: 'engranaje gear' },
  { char: '⚖️', category: 'objects', tags: 'balanza justice justicia' },
  { char: '🔗', category: 'objects', tags: 'enlace link' },
  { char: '⚔️', category: 'objects', tags: 'espadas swords lucha fight espases' },
  { char: '🛡️', category: 'objects', tags: 'escudo shield proteccion escut' },
  { char: '🏹', category: 'objects', tags: 'arco flecha bow arrow arc' },
  { char: '🔫', category: 'objects', tags: 'pistola gun' },
  { char: '💣', category: 'objects', tags: 'bomba bomb' },
  { char: '🧨', category: 'objects', tags: 'dinamita firecracker' },
  { char: '💎', category: 'objects', tags: 'diamante diamond joya jewel diamant' },
  { char: '💍', category: 'objects', tags: 'anillo ring joya jewel anell' },
  { char: '👑', category: 'objects', tags: 'corona crown rey king reina queen' },
  { char: '🎩', category: 'objects', tags: 'sombrero hat ropa clothes barret' },
  { char: '👕', category: 'objects', tags: 'camiseta shirt ropa clothes samarreta' },
  { char: '👗', category: 'objects', tags: 'vestido dress ropa clothes vestit' },
  { char: '🎒', category: 'objects', tags: 'mochila backpack colegio school motxilla' },
  { char: '👓', category: 'objects', tags: 'gafas glasses' },
  { char: '🕶️', category: 'objects', tags: 'gafas sol sunglasses ulleres' },
  { char: '🔭', category: 'objects', tags: 'telescopio espacio space telescopi' },
  { char: '🛰️', category: 'objects', tags: 'satelite space espacio satèl·lit' },
  { char: '📱', category: 'objects', tags: 'movil phone' },
  { char: '💻', category: 'objects', tags: 'ordenador computer laptop' },
  { char: '📷', category: 'objects', tags: 'camara camera' },
  { char: '🔋', category: 'objects', tags: 'bateria battery' },

  // Symbols
  { char: '❤️', category: 'symbols', tags: 'corazon heart amor love rojo red cor' },
  { char: '🧡', category: 'symbols', tags: 'corazon heart naranja orange cor' },
  { char: '💛', category: 'symbols', tags: 'corazon heart amarillo yellow cor' },
  { char: '💚', category: 'symbols', tags: 'corazon heart verde green cor' },
  { char: '💙', category: 'symbols', tags: 'corazon heart azul blue cor' },
  { char: '💜', category: 'symbols', tags: 'corazon heart lila purple cor' },
  { char: '🖤', category: 'symbols', tags: 'corazon heart negro black cor' },
  { char: '💔', category: 'symbols', tags: 'corazon roto broken heart cor' },
  { char: '✨', category: 'symbols', tags: 'brillos sparkles brillants' },
  { char: '💥', category: 'symbols', tags: 'explosion explosió' },
  { char: '💨', category: 'symbols', tags: 'humo wind rapido fast fum vent' },
  { char: '💦', category: 'symbols', tags: 'agua water gotas aigua' },
  { char: '💤', category: 'symbols', tags: 'dormir sleep' },
  { char: '🔥', category: 'symbols', tags: 'fuego fire calor foc' },
  { char: '☀️', category: 'symbols', tags: 'sol sun tiempo weather calor' },
  { char: '⭐', category: 'symbols', tags: 'estrella star' },
  { char: '🌟', category: 'symbols', tags: 'estrella star' },
  { char: '🌈', category: 'symbols', tags: 'arcoiris rainbow tiempo weather arc de sant martí' },
  { char: '❄️', category: 'symbols', tags: 'nieve snow frio cold tiempo weather neu' },
  { char: '💯', category: 'symbols', tags: 'cien hundred' },
  { char: '✅', category: 'symbols', tags: 'bien ok check' },
  { char: '❌', category: 'symbols', tags: 'mal no cross' },
  { char: '⚠️', category: 'symbols', tags: 'peligro warning' },
  { char: '🛑', category: 'symbols', tags: 'parar stop' },
  { char: '🟢', category: 'symbols', tags: 'verde green' },
  { char: '🔴', category: 'symbols', tags: 'rojo red' },
  { char: '🔵', category: 'symbols', tags: 'azul blue' },
]
