export const EMOJI_LIBRARY = [
  // Animals
  { char: '🐶', tags: 'perro dog animal mascota gos' },
  { char: '🐱', tags: 'gato cat animal mascota gat' },
  { char: '🐭', tags: 'raton mouse animal ratolí' },
  { char: '🐹', tags: 'hamster animal mascota hàmster' },
  { char: '🐰', tags: 'conejo rabbit animal conill' },
  { char: '🦊', tags: 'zorro fox animal guineu' },
  { char: '🐻', tags: 'oso bear animal os' },
  { char: '🐼', tags: 'panda animal' },
  { char: '🐨', tags: 'koala animal' },
  { char: '🐯', tags: 'tigre tiger animal' },
  { char: '🦁', tags: 'leon lion animal lleó' },
  { char: '🐮', tags: 'vaca cow animal' },
  { char: '🐷', tags: 'cerdo pig animal porc' },
  { char: '🐸', tags: 'rana frog animal granota' },
  { char: '🐵', tags: 'mono monkey animal mico' },
  { char: '🐔', tags: 'pollo chicken gallina animal gallina' },
  { char: '🐧', tags: 'pinguino penguin animal pingüí' },
  { char: '🐦', tags: 'pajaro bird animal ocell' },
  { char: '🐤', tags: 'pollito ocellet' },
  { char: '🦆', tags: 'pato duck animal ànec' },
  { char: '🦅', tags: 'aguila eagle animal àguila' },
  { char: '🦉', tags: 'buho owl animal mussol' },
  { char: '🦇', tags: 'murcielago bat animal ratpenat' },
  { char: '🐺', tags: 'lobo wolf animal llop' },
  { char: '🐗', tags: 'jabalí boar animal senglar' },
  { char: '🐴', tags: 'caballo horse animal cavall' },
  { char: '🦄', tags: 'unicornio fantasy unicorni' },
  { char: '🐝', tags: 'abeja bee insecto abella' },
  { char: '🐛', tags: 'gusano bug insecto cuc' },
  { char: '🦋', tags: 'mariposa butterfly insecto papallona' },
  { char: '🐌', tags: 'caracol snail insecto caragol' },
  { char: '🐞', tags: 'mariquita ladybug insecto marieta' },
  { char: '🐜', tags: 'hormiga ant insecto formiga' },
  { char: '🦗', tags: 'grillo cricket insecto grill' },
  { char: '🕷️', tags: 'araña spider insecto aranya' },
  { char: '🦂', tags: 'escorpion scorpion insecto escorpí' },
  { char: '🐢', tags: 'tortuga turtle animal' },
  { char: '🐍', tags: 'serpiente snake animal serp' },
  { char: '🦎', tags: 'lagartija lizard animal sargantana' },
  { char: '🦖', tags: 'dinosaurio t-rex' },
  { char: '🐙', tags: 'pulpo octopus mar ocean pop' },
  { char: '🦑', tags: 'calamar squid mar ocean' },
  { char: '🦐', tags: 'gamba shrimp mar ocean' },
  { char: '🦞', tags: 'langosta lobster mar ocean llagosta' },
  { char: '🦀', tags: 'cangrejo crab mar ocean cranc' },
  { char: '🐡', tags: 'pez globo pufferfish mar ocean peix' },
  { char: '🐠', tags: 'pez tropical fish mar ocean peix' },
  { char: '🐟', tags: 'pez fish mar ocean peix' },
  { char: '🐬', tags: 'delfin dolphin mar ocean dofí' },
  { char: '🐳', tags: 'ballena whale mar ocean balena' },
  { char: '🦈', tags: 'tiburon shark mar ocean tauró' },
  { char: '🐊', tags: 'cocodrilo crocodile animal cocodril' },

  // Food & Drink
  { char: '🍎', tags: 'manzana apple fruta fruit comida food poma' },
  { char: '🍐', tags: 'pera pear fruta fruit comida food' },
  { char: '🍊', tags: 'naranja orange fruta fruit comida food taronja' },
  { char: '🍋', tags: 'limon lemon fruta fruit comida food llimona' },
  { char: '🍌', tags: 'platano banana fruta fruit comida food plàtan' },
  { char: '🍉', tags: 'sandia watermelon fruta fruit comida food síndria' },
  { char: '🍇', tags: 'uvas grapes fruta fruit comida food raïm' },
  { char: '🍓', tags: 'fresa strawberry fruta fruit comida food maduixa' },
  { char: '🍒', tags: 'cerezas cherries fruta fruit comida food cireres' },
  { char: '🍑', tags: 'melocoton peach fruta fruit comida food préssec' },
  { char: '🍍', tags: 'piña pineapple fruta fruit comida food pinya' },
  { char: '🥥', tags: 'coco coconut fruta fruit comida food' },
  { char: '🥝', tags: 'kiwi fruta fruit comida food' },
  { char: '🍅', tags: 'tomate tomato verdura vegetable comida food tomàquet' },
  { char: '🥦', tags: 'brocoli broccoli verdura vegetable comida food bròquil' },
  { char: '🥑', tags: 'aguacate avocado comida food alvocat' },
  { char: '🍆', tags: 'berenjena eggplant verdura vegetable comida food albergínia' },
  { char: '🥔', tags: 'patata potato verdura vegetable comida food' },
  { char: '🥕', tags: 'zanahoria carrot verdura vegetable comida food pastanaga' },
  { char: '🌽', tags: 'maiz corn comida food blat de moro' },
  { char: '🌶️', tags: 'picante chili comida food' },
  { char: '🍄', tags: 'seta mushroom comida food bolets' },
  { char: '🥜', tags: 'cacahuetes peanuts comida food cacauets' },
  { char: '🥐', tags: 'cruasan croissant comida food pan cruixent' },
  { char: '🍞', tags: 'pan bread comida food pa' },
  { char: '🥨', tags: 'pretzel comida food' },
  { char: '🧀', tags: 'queso cheese comida food formatge' },
  { char: '🥩', tags: 'carne meat comida food carn' },
  { char: '🍗', tags: 'pollo chicken comida food pollastre' },
  { char: '🍔', tags: 'hamburguesa burger comida food fastfood' },
  { char: '🍟', tags: 'patatas fritas fries comida food fastfood patates' },
  { char: '🍕', tags: 'pizza comida food fastfood' },
  { char: '🌭', tags: 'perrito caliente hotdog comida food fastfood' },
  { char: '🌮', tags: 'taco comida food' },
  { char: '🌯', tags: 'burrito comida food' },
  { char: '🥚', tags: 'huevo egg comida food desayuno ou' },
  { char: '🥣', tags: 'sopa soup comida food' },
  { char: '🍿', tags: 'palomitas popcorn comida food cine crispetes' },
  { char: '🍱', tags: 'bento comida food japones' },
  { char: '🍣', tags: 'sushi comida food japones' },
  { char: '🍦', tags: 'helado icecream postre sweet comida food gelat' },
  { char: '🍩', tags: 'donut postre sweet comida food' },
  { char: '🍪', tags: 'galleta cookie postre sweet comida food galeta' },
  { char: '🎂', tags: 'pastel cake postre sweet comida food cumple pastís' },
  { char: '🍫', tags: 'chocolate postre sweet comida food xocolata' },
  { char: '🍬', tags: 'caramelo candy postre sweet comida food' },
  { char: '🍭', tags: 'piruleta lollipop postre sweet comida food' },
  { char: '🍮', tags: 'flan postre sweet comida food' },
  { char: '🍯', tags: 'miel honey postre sweet comida food mel' },
  { char: '☕', tags: 'cafe coffee bebida drink cafè' },
  { char: '🍵', tags: 'te tea bebida drink tè' },
  { char: '🥤', tags: 'refresco soda bebida drink' },
  { char: '🍺', tags: 'cerveza beer bebida drink alcohol cervesa' },
  { char: '🍷', tags: 'vino wine bebida drink alcohol vi' },
  { char: '🍹', tags: 'coctel cocktail bebida drink còctel' },

  // Nature & Weather
  { char: '☀️', tags: 'sol sun tiempo weather calor' },
  { char: '🌙', tags: 'luna moon noche night lluna' },
  { char: '⭐', tags: 'estrella star' },
  { char: '☁️', tags: 'nube cloud tiempo weather núvol' },
  { char: '⛅', tags: 'nubes sol cloud sun' },
  { char: '⛈️', tags: 'tormenta storm tiempo weather rayo tempesta' },
  { char: '🌤️', tags: 'sol nubes' },
  { char: '❄️', tags: 'nieve snow frio cold tiempo weather neu' },
  { char: '🌪️', tags: 'tornado tiempo weather' },
  { char: '🌈', tags: 'arcoiris rainbow tiempo weather arc de sant martí' },
  { char: '🌊', tags: 'ola wave mar ocean agua water ona' },
  { char: '💧', tags: 'gota drop agua water' },
  { char: '🔥', tags: 'fuego fire calor foc' },
  { char: '🌵', tags: 'cactus desierto desert nature' },
  { char: '🎄', tags: 'arbol navidad christmas tree arbre' },
  { char: '🌲', tags: 'pino tree arbol nature pi' },
  { char: '🌳', tags: 'arbol tree nature arbre' },
  { char: '🌴', tags: 'palmera palm tree nature' },
  { char: '🌱', tags: 'planta plant nature' },
  { char: '🌿', tags: 'hierba herb nature herba' },
  { char: '☘️', tags: 'trebol clover nature trèvol' },
  { char: '🍀', tags: 'trebol suerte lucky nature trèvol' },
  { char: '🍃', tags: 'hojas leaves nature fulles' },
  { char: '🍂', tags: 'otoño autumn hojas leaves nature tardor' },
  { char: '🍁', tags: 'maple autumn hojas leaves nature' },
  { char: '🍄', tags: 'seta mushroom nature bolet' },
  { char: '🌸', tags: 'flor flower primavera spring' },
  { char: '🌹', tags: 'rosa rose flor flower amor love' },
  { char: '🌻', tags: 'girasol sunflower flor flower' },
  { char: '🌼', tags: 'flor flower primavera spring' },
  { char: '🌷', tags: 'tulipan tulip flor flower tulipa' },

  // Activities & Objects
  { char: '⚽', tags: 'futbol soccer deporte sport pelota ball' },
  { char: '🏀', tags: 'baloncesto basketball deporte sport pelota ball bàsquet' },
  { char: '🏈', tags: 'rugby deporte sport pelota ball' },
  { char: '⚾', tags: 'beisbol baseball deporte sport pelota ball' },
  { char: '🎾', tags: 'tenis tennis deporte sport pelota ball' },
  { char: '🏐', tags: 'voleyball deporte sport pelota ball' },
  { char: '🎱', tags: 'billar deporte sport pelota ball' },
  { char: '🏓', tags: 'pingpong deporte sport' },
  { char: '🏸', tags: 'badminton deporte sport' },
  { char: '🥅', tags: 'porteria deporte sport' },
  { char: '⛳', tags: 'golf deporte sport' },
  { char: '⛸️', tags: 'patinaje hielo deporte sport patinatge' },
  { char: '🎣', tags: 'pesca fishing deporte sport' },
  { char: '🛶', tags: 'canoa kayak deporte sport' },
  { char: '🏄', tags: 'surf deporte sport mar' },
  { char: '🏇', tags: 'carreras caballos deporte sport cavalls' },
  { char: '🚲', tags: 'ciclismo bici bike deporte sport' },
  { char: '🏆', tags: 'trofeo trophy ganador winner premio trofeu' },
  { char: '🏅', tags: 'medalla medal ganador winner' },
  { char: '🥇', tags: 'primero first medalla' },
  { char: '🎸', tags: 'guitarra music musica instrumento' },
  { char: '🎹', tags: 'piano music musica instrumento' },
  { char: '🎷', tags: 'saxofon music musica instrumento' },
  { char: '🎺', tags: 'trompeta music musica instrumento' },
  { char: '🎻', tags: 'violin music musica instrumento' },
  { char: '🥁', tags: 'tambor music musica instrumento' },
  { char: '🎧', tags: 'auriculares music musica auriculars' },
  { char: '🎤', tags: 'microfono music musica cantar' },
  { char: '🎨', tags: 'arte art pintura paint' },
  { char: '🎬', tags: 'cine movie pelicula' },
  { char: '🎮', tags: 'videojuegos game mando' },
  { char: '🎲', tags: 'dados dice juego game daus' },
  { char: '🧩', tags: 'puzzle rompecabezas' },
  { char: '🚗', tags: 'coche car transporte transport cotxe' },
  { char: '🚕', tags: 'taxi transporte transport' },
  { char: '🚌', tags: 'autobus bus transporte transport autobús' },
  { char: '🏎️', tags: 'carreras car transporte transport' },
  { char: '🚓', tags: 'policia police transporte transport policia' },
  { char: '🚑', tags: 'ambulancia transporte transport' },
  { char: '🚒', tags: 'bomberos transporte transport bombers' },
  { char: '🚲', tags: 'bici bike transporte transport' },
  { char: '🛵', tags: 'moto transporte transport' },
  { char: '🏍️', tags: 'moto transporte transport' },
  { char: '🚆', tags: 'tren train transporte transport' },
  { char: '✈️', tags: 'avion plane transporte transport viajar travel avió' },
  { char: '🚀', tags: 'cohete rocket espacio space transporte transport coet' },
  { char: '🚁', tags: 'helicoptero transporte transport helicòpter' },
  { char: '⛵', tags: 'barco boat transporte transport mar vaixell' },
  { char: '🚢', tags: 'crucero ship transporte transport mar vaixell' },
  { char: '🛸', tags: 'ovni ufo espacio space alien' },

  // Space
  { char: '🌍', tags: 'tierra earth mundo world planeta planet terra' },
  { char: '🌕', tags: 'luna llena moon noche lluna' },
  { char: '🌑', tags: 'luna nueva moon noche lluna' },
  { char: '🌓', tags: 'luna cuarto moon noche lluna' },
  { char: '☀️', tags: 'sol sun estrella' },
  { char: '⭐', tags: 'estrella star' },
  { char: '🌟', tags: 'estrella star' },
  { char: '☄️', tags: 'cometa comet' },
  { char: '🪐', tags: 'saturno saturn planeta planet' },
  { char: '🔭', tags: 'telescopio espacio space telescopi' },
  { char: '🛰️', tags: 'satelite space espacio satèl·lit' },
  { char: '👽', tags: 'alien espacio space extraterrestre' },
  { char: '👾', tags: 'monstruo monster espacio space' },

  // Symbols & Hearts
  { char: '❤️', tags: 'corazon heart amor love rojo red cor' },
  { char: '🧡', tags: 'corazon heart naranja orange cor' },
  { char: '💛', tags: 'corazon heart amarillo yellow cor' },
  { char: '💚', tags: 'corazon heart verde green cor' },
  { char: '💙', tags: 'corazon heart azul blue cor' },
  { char: '💜', tags: 'corazon heart lila purple cor' },
  { char: '🖤', tags: 'corazon heart negro black cor' },
  { char: '💔', tags: 'corazon roto broken heart cor' },
  { char: '❣️', tags: 'exclamacion corazon cor' },
  { char: '💕', tags: 'corazones hearts cors' },
  { char: '💖', tags: 'corazon brillante cor' },
  { char: '💗', tags: 'corazon creciente cor' },
  { char: '💘', tags: 'flechazo amor cupid cor' },
  { char: '💝', tags: 'regalo corazon cor' },
  { char: '💟', tags: 'corazon decorativo cor' },
  { char: '✨', tags: 'brillos sparkles brillants' },
  { char: '💥', tags: 'explosion explosió' },
  { char: '💣', tags: 'bomba bomb' },
  { char: '💨', tags: 'humo wind rapido fast fum vent' },
  { char: '💦', tags: 'agua water gotas aigua' },
  { char: '💤', tags: 'dormir sleep' },
  { char: '💡', tags: 'idea luz light bombilla llum' },
  { char: '🔍', tags: 'lupa search buscar' },
  { char: '🔑', tags: 'llave key clau' },
  { char: '🔒', tags: 'candado lock candau' },
  { char: '🔓', tags: 'candado abierto unlock' },
  { char: '🔨', tags: 'martillo hammer herramienta tool martell' },
  { char: '🛠️', tags: 'herramientas tools martillo pico eines' },
  { char: '⛏️', tags: 'pico pickaxe herramienta tool pic' },
  { char: '⚙️', tags: 'engranaje gear' },
  { char: '⚖️', tags: 'balanza justice justicia' },
  { char: '🔗', tags: 'enlace link' },
  { char: '⚔️', tags: 'espadas swords lucha fight espases' },
  { char: '🛡️', tags: 'escudo shield proteccion escut' },
  { char: '🏹', tags: 'arco flecha bow arrow arc' },
  { char: '🔫', tags: 'pistola gun' },
  { char: '💣', tags: 'bomba bomb' },
  { char: '🧨', tags: 'dinamita firecracker' },
  { char: '⚰️', tags: 'ataud coffin muerte death ataüt' },
  { char: '⚱️', tags: 'urna funeral muerte death' },
  { char: '💎', tags: 'diamante diamond joya jewel diamant' },
  { char: '💍', tags: 'anillo ring joya jewel anell' },
  { char: '👑', tags: 'corona crown rey king reina queen' },
  { char: '🎩', tags: 'sombrero hat ropa clothes barret' },
  { char: '👕', tags: 'camiseta shirt ropa clothes samarreta' },
  { char: '👗', tags: 'vestido dress ropa clothes vestit' },
  { char: '👠', tags: 'zapatos shoes ropa clothes tacones sabates' },
  { char: '👟', tags: 'zapatillas sneakers ropa clothes deporte' },
  { char: '🎒', tags: 'mochila backpack colegio school motxilla' },
  { char: '🕶️', tags: 'gafas sol sunglasses ulleres' },

  // People & Faces
  { char: '😀', tags: 'feliz happy sonrisa smile' },
  { char: '😂', tags: 'risa laugh llorar risa riure' },
  { char: '🤣', tags: 'risa laugh riure' },
  { char: '😊', tags: 'feliz happy sonrisa smile feliç' },
  { char: '😇', tags: 'angel inocente àngel' },
  { char: '😍', tags: 'enamorado love' },
  { char: '🤩', tags: 'estrella ojos wow' },
  { char: '😘', tags: 'beso kiss amor love petó' },
  { char: '😋', tags: 'comida rico yummy' },
  { char: '😛', tags: 'lengua tongue llengua' },
  { char: '😜', tags: 'lengua guiño' },
  { char: '🤪', tags: 'loco crazy boig' },
  { char: '🤨', tags: 'duda sceptic' },
  { char: '🧐', tags: 'monoculo investigar' },
  { char: '🤓', tags: 'empollon nerd' },
  { char: '😎', tags: 'guay cool sol sunglasses' },
  { char: '🥳', tags: 'fiesta party celebracion festa' },
  { char: '😏', tags: 'pillo' },
  { char: '😒', tags: 'aburrido bored' },
  { char: '😞', tags: 'triste sad trist' },
  { char: '😔', tags: 'triste sad trist' },
  { char: '😟', tags: 'preocupado worried' },
  { char: '😕', tags: 'confundido confused' },
  { char: '🙁', tags: 'triste sad trist' },
  { char: '☹️', tags: 'muy triste sad' },
  { char: '😣', tags: 'sufrimiento' },
  { char: '😖', tags: 'confundido' },
  { char: '😫', tags: 'cansado tired cansat' },
  { char: '😩', tags: 'cansado tired cansat' },
  { char: '🥺', tags: 'por favor please' },
  { char: '😢', tags: 'llorar cry triste sad plorar' },
  { char: '😭', tags: 'llorar mucho cry sad plorar' },
  { char: '😤', tags: 'enfadado angry' },
  { char: '😠', tags: 'enfadado angry enfadat' },
  { char: '😡', tags: 'muy enfadado angry rojo red enfadat' },
  { char: '🤬', tags: 'insulto enfadado' },
  { char: '🤯', tags: 'cabeza explota wow mindblown' },
  { char: '😳', tags: 'sonrojado' },
  { char: '🥵', tags: 'calor hot rojo red' },
  { char: '🥶', tags: 'frio cold azul blue fred' },
  { char: '😱', tags: 'miedo fear susto wow por' },
  { char: '😨', tags: 'miedo fear por' },
  { char: '😰', tags: 'miedo miedo por' },
  { char: '😥', tags: 'alivio' },
  { char: '😓', tags: 'sudor' },
  { char: '🤗', tags: 'abrazo hug abraçada' },
  { char: '🤔', tags: 'pensar think duda' },
  { char: '🤭', tags: 'secreto' },
  { char: '🤫', tags: 'silencio shh silenci' },
  { char: '🤥', tags: 'mentira lie pinocho mentida' },
  { char: '😶', tags: 'sin palabras' },
  { char: '😐', tags: 'neutral' },
  { char: '😑', tags: 'sin expresion' },
  { char: '😬', tags: 'mueca' },
  { char: '🙄', tags: 'ojos arriba roll eyes' },
  { char: '😯', tags: 'sorpresa surprise wow' },
  { char: '😦', tags: 'sorpresa surprise' },
  { char: '😧', tags: 'sorpresa surprise' },
  { char: '😮', tags: 'sorpresa surprise wow' },
  { char: '😲', tags: 'sorpresa surprise wow' },
  { char: '😴', tags: 'dormir sleep' },
  { char: '🤤', tags: 'baba' },
  { char: '😪', tags: 'dormir sleep' },
  { char: '😵', tags: 'mareado' },
  { char: '🤐', tags: 'boca cerrada' },
  { char: '🥴', tags: 'borracho' },
  { char: '🤢', tags: 'asco' },
  { char: '🤮', tags: 'vomitar' },
  { char: '🤧', tags: 'estornudar' },
  { char: '🤒', tags: 'fiebre enfermo febre' },
  { char: '🤕', tags: 'herida enfermo ferida' },
  { char: '🤑', tags: 'dinero money diners' },
  { char: '🤠', tags: 'vaquero cowboy' },
  { char: '😈', tags: 'diablo devil malo' },
  { char: '👿', tags: 'diablo devil' },
  { char: '👹', tags: 'ogro monster' },
  { char: '👺', tags: 'duende monster' },
  { char: '🤡', tags: 'payaso clown pallasso' },
  { char: '💩', tags: 'caca poop' },
  { char: '👻', tags: 'fantasma ghost miedo por' },
  { char: '💀', tags: 'calavera skull muerte death calavera' },
  { char: '☠️', tags: 'pirata death muerte' },
  { char: '👽', tags: 'alien espacio space' },
  { char: '👾', tags: 'monstruo space' },
  { char: '🤖', tags: 'robot' },
  { char: '🎃', tags: 'calabaza halloween carbassa' },

  // Hands & Body
  { char: '👋', tags: 'hola adios mano hand wave' },
  { char: '🤚', tags: 'mano hand stop' },
  { char: '🖐️', tags: 'mano hand' },
  { char: '✋', tags: 'mano hand stop' },
  { char: '🖖', tags: 'vulcano space' },
  { char: '👌', tags: 'ok bien' },
  { char: '✌️', tags: 'paz victoria peace pau' },
  { char: '🤞', tags: 'suerte luck sort' },
  { char: '🤟', tags: 'amor love rock' },
  { char: '🤘', tags: 'rock metal' },
  { char: '🤙', tags: 'llamar call' },
  { char: '👈', tags: 'izquierda left dedo esquerra' },
  { char: '👉', tags: 'derecha right dedo dreta' },
  { char: '👆', tags: 'arriba up dedo' },
  { char: '🖕', tags: 'insulto finger' },
  { char: '👇', tags: 'abajo down dedo' },
  { char: '☝️', tags: 'uno one dedo un' },
  { char: '👍', tags: 'bien like ok' },
  { char: '👎', tags: 'mal dislike' },
  { char: '✊', tags: 'puño fist' },
  { char: '👊', tags: 'puño fist peguntar puny' },
  { char: '🤛', tags: 'puño fist puny' },
  { char: '🤜', tags: 'puño fist puny' },
  { char: '👏', tags: 'aplauso clap' },
  { char: '🙌', tags: 'celebracion' },
  { char: '👐', tags: 'manos abiertas mans' },
  { char: '🤲', tags: 'rezar' },
  { char: '🤝', tags: 'trato deal manos' },
  { char: '🙏', tags: 'por favor gracias please thanks gràcies' },
  { char: '✍️', tags: 'escribir write escriure' },
  { char: '💅', tags: 'uñas nails ungles' },
  { char: '🤳', tags: 'selfie' },
  { char: '💪', tags: 'fuerza strong musculo força' },
  { char: '👂', tags: 'oreja ear oir listen orella' },
  { char: '👃', tags: 'nariz nose oler smell nas' },
  { char: '🧠', tags: 'cerebro brain pensar think cervell' },
  { char: '👀', tags: 'ojos eyes mirar watch ulls' },
  { char: '👁️', tags: 'ojo eye mirar ull' },
  { char: '👅', tags: 'lengua tongue llengua' },
  { char: '👄', tags: 'boca mouth beso kiss' },
];
