services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: astro_backend_prod
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - astro_network

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.prod
    container_name: astro_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - astro_network

networks:
  astro_network:
    driver: bridge