services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: astro_backend_prod
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.prod
    container_name: astro_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      # AQUÍ ESTÁ EL CAMBIO CLAVE: La ruta correcta hacia tu nginx.conf
      - ./frontend/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend