services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: astro_backend_prod
    restart: unless-stopped
    env_file:
      - ./backend/.env
    # No necesita "ports" porque Nginx hablará con él internamente

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile.prod
    container_name: astro_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"   # Redirección
      - "443:443" # El candadito
    volumes:
      # 1. Tu archivo de configuración de Nginx retocado
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 2. Los certificados de Let's Encrypt del servidor real
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend