services:
  mongodb:
    image: mongo:latest
    container_name: astro_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: astro_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Evita que los nodos locales sobrescriban los del contenedor
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/astro_db
      - PORT=3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: astro_frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ayuda al hot-reload en algunos sistemas
    depends_on:
      - backend

volumes:
  mongo_data: